# Generated by Django 3.2.8 on 2022-04-01 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_remove_producto_id_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda.marca'),
            preserve_default=False,
        ),
    ]
