# Generated by Django 3.2.8 on 2022-04-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_producto_id_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_marca',
            field=models.TextField(),
        ),
    ]
