# Generated by Django 3.2.8 on 2022-04-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_remove_producto_id_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='suit',
            field=models.IntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=1),
        ),
    ]
