# Generated by Django 3.2.8 on 2022-04-01 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_producto_suit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='suit',
            new_name='estado',
        ),
    ]
