# Generated by Django 3.2.8 on 2022-04-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0016_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='cantidad',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
