# Generated by Django 3.2.8 on 2022-04-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0017_carrito_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='precio',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
