# Generated by Django 3.2.8 on 2022-04-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0018_alter_carrito_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('pais', models.TextField()),
                ('direccion', models.TextField()),
                ('direccion_aux', models.TextField(blank=True, null=True)),
                ('departamento', models.TextField()),
                ('ciudad', models.TextField()),
                ('codigo_postal', models.TextField(blank=True, null=True)),
                ('telefono', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
