# Generated by Django 3.2.8 on 2022-04-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0021_orden_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_ventas',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pago en proceso', 'Pago en proceso'), ('Pago aceptado', 'Pago aceptado'), ('En trámite', 'En trámite'), ('Despachado', 'Despachado')], max_length=200, null=True),
        ),
    ]
