# Generated by Django 3.2.8 on 2022-04-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0022_orden_ventas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_ventas',
            name='session_id',
            field=models.TextField(editable=False),
        ),
    ]
