# Generated by Django 3.2.8 on 2022-04-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0023_alter_orden_ventas_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='cedula',
            field=models.TextField(blank=True, null=True),
        ),
    ]
